// shortcuts.js
export const shortcuts = [
  {
    keys: [" "],
    action: "togglePlay",
    label: "Play / Pause",
    display: ["Space"],
  },
  { keys: ["k"], action: "togglePlay", label: "Play / Pause", display: ["k"] },

  {
    keys: ["l", "ArrowRight"],
    action: "seekForward",
    label: "Seek Forward 10s",
    display: ["l", "→"],
  },
  {
    keys: ["j", "ArrowLeft"],
    action: "seekBackward",
    label: "Seek Backward 10s",
    display: ["j", "←"],
  },
  { keys: ["ArrowUp"], action: "volumeUp", label: "Volume Up", display: ["↑"] },
  {
    keys: ["ArrowDown"],
    action: "volumeDown",
    label: "Volume Down",
    display: ["↓"],
  },
  { keys: ["m"], action: "toggleMute", label: "Mute / Unmute", display: ["m"] },
  {
    keys: ["e"],
    action: "toggleEditMode",
    label: "Toggle Edit Mode",
    display: ["e"],
  },
  {
    keys: ["/"],
    action: "focusSearch",
    label: "Focus Search Bar",
    display: ["/"],
  },
  {
    keys: ["?"],
    shift: true,
    action: "openShortcuts",
    label: "Toggles Shortcut Cheat Sheet",
    display: ["Shift + /"],
  },
  {
    keys: ["t"],
    shift: true,
    action: "toggleTheme",
    label: "Toggles Theme",
    display: ["Shift + t"],
  },
  {
    keys: ["n"],
    shift: true,
    action: "nextSong",
    label: "Next Song",
    display: ["Shift + n"],
  },
  {
    keys: ["p"],
    shift: true,
    action: "prevSong",
    label: "Previous Song",
    display: ["Shift + p"],
  },
  {
    keys: [">"],
    shift: true,
    action: "speedUp",
    label: "Increase Speed",
    display: ["Shift + >"],
  },
  {
    keys: ["<"],
    shift: true,
    action: "speedDown",
    label: "Decrease Speed",
    display: ["Shift + <"],
  },
];
